var nutriInfo = [
    {'name':'Calories','percentage':'9%'},
    {'name':'Dietary Fiber','percentage':'1%'},
    {'name':'Total Fat','percentage':'25%'},
    {'name':'Protein','percentage':'13%'},
    {'name':'Vitamin B-6','percentage':'8%'},
    {'name':'Pantothenic','percentage':'5%'},
    {'name':'Iron','percentage':'5%'},
    {'name':'Magnesium','percentage':'14%'},
    {'name':'Photsphorus','percentage':'14%'},
    {'name':'Zinc','percentage':'6%'},
    {'name':'Copper','percentage':'19%'},
    {'name':'Manganese','percentage':'55%'},
    {'name':'Selenium','percentage':'7%'},
    

    {'name':'Calories','percentage':'8%'},
    {'name':'Total Fat','percentage':'20%'},
    {'name':'Protein','percentage':'9%'},
    {'name':'Vitamin K','percentage':'12%'},
    {'name':'Iron','percentage':'9%'},
    {'name':'Magnesium','percentage':'18%'},
    {'name':'Phosphorus','percentage':'14%'},
    {'name':'Potassium','percentage':'5%'},
    {'name':'Zinc','percentage':'10%'},
    {'name':'Copper','percentage':'31%'},
    {'name':'Manganese','percentage':'12%'},
    {'name':'Selenium','percentage':'5%'},

    {'name':'Dietary Fiber','percentage':'9%'},
    {'name':'Total Fat','percentage':'21%'},
    {'name':'Protein','percentage':'13%'},
    {'name':'Vitamin E','percentage':'10%'},
    {'name':'Vitamin K','percentage':'3%'},
    {'name':'Niacin','percentage':'19%'},
    {'name':'Magnesium','percentage':'12%'},
    {'name':'Photsphorus','percentage':'10%'},
    {'name':'Copper','percentage':'9%'},
    {'name':'Manganese','percentage':'29%'},

    {'name':'Manganese','percentage':'29%'},

    {'name':'Carbohydrate','percentage':'7%'},
    {'name':'Dietary Fiber','percentage':'14%'},
    {'name':'Sugar','percentage':'70%'},
    {'name':'Vitamin K','percentage':'36%'},
    {'name':'Manganese','percentage':'25%'},

    {'name':'Dietary Fiber','percentage':'9%'},
    {'name':'Protein','percentage':'5%'},
    {'name':'Vitamin A','percentage':'11%'},
    {'name':'Vitamin C','percentage':'135%'},
    {'name':'Vitamin K','percentage':'4%'},
    {'name':'Riboflavin','percentage':'6%'},
    {'name':'Vitamin B-6','percentage':'8%'},
    {'name':'Pantothetic','percentage':'5%'},
    {'name':'Magnesium','percentage':'5%'},
    {'name':'Phosphorus','percentage':'6%'},
    {'name':'Potassium','percentage':'8%'},
    {'name':'Manganese','percentage':'10%'},

    {'name':'Calories','percentage':'7%'},
    {'name':'Total Fat','percentage':'18%'},
    {'name':'Protein','percentage':'18%'},
    {'name':'Thiamin','percentage':'17%'},
    {'name':'Riboflav','percentage':'5%'},
    {'name':'Iron','percentage':'23%'},
    {'name':'Magnesium','percentage':'37%'},
    {'name':'Photsphorus','percentage':'33%'},
    {'name':'Potassium','percentage':'6%'},
    {'name':'Zinc','percentage':'14%'},
    {'name':'Copper','percentage':'19%'},

    {'name':'Carbonhydrate','percentage':'7%'},
    {'name':'Vitamin A','percentage':'8%'},
    {'name':'Vitamin C','percentage':'145%'},
    {'name':'Riboflav','percentage':'4%'},
    {'name':'Vitamin B-6','percentage':'6%'},
    {'name':'Vitamin','percentage':'10%'},
    {'name':'Iron','percentage':'1%'},
    {'name':'Potassium','percentage':'9%'},

    {'name':'Calories','percentage':'5%'},
    {'name':'Carbohydrate','percentage':'6%'},
    {'name':'Dietary Fiber','percentage':'34'},
    {'name':'Thiamin','percentage':'16%'},
    {'name':'Vitamin B-6','percentage':'8%'},
    {'name':'Vitamin B-12','percentage':'34%'},
    {'name':'Iron','percentage':'12%'},
    {'name':'Magnesium','percentage':'9%'},
    {'name':'Photsphorus','percentage':'13%'},
    {'name':'Potassium','percentage':'8%'},
    {'name':'Zinc','percentage':'9%'},
    {'name':'Copper','percentage':'7%'},
    {'name':'Manganese','percentage':'10%'},

    {'name':'Carbonhydrate','percentage':'7%'},
    {'name':'Vitamin A','percentage':'12%'},
    {'name':'Vitamin C','percentage':'146%'},
    {'name':'Vitamin B-6','percentage':'3%'},
    {'name':'Pantothetic','percentage':'7%'},
    {'name':'Magnesium','percentage':'5%'},
    {'name':'Potassium','percentage':'3%'},

    {'name':'Dietary Fiber','percentage':'34%'},
    {'name':'Vitamin K','percentage':'181%'},
    {'name':'Magnesium','percentage':'6%'},
    {'name':'Potassium','percentage':'5%'},
    {'name':'Manganese','percentage':'13%'},

    {'name':'Dietary Fiber','percentage':'5%'},
    {'name':'Vitamin A','percentage':'206%'},
    {'name':'Vitamin C','percentage':'134%'},
    {'name':'Vitamin K','percentage':'684%'},
    {'name':'Riboflav','percentage':'5%'},
    {'name':'Vitamin B-6','percentage':'9%'},
    {'name':'Calcium','percentage':'9%'},
    {'name':'Iron','percentage':'6%'},
    {'name':'Magnesium','percentage':'6%'},
    {'name':'Potassium','percentage':'9%'},
    {'name':'Copper','percentage':'10%'},
    {'name':'Manganese','percentage':'26%'},

    {'name':'Dietary Fiber','percentage':'5%'},
    {'name':'Vitamin A','percentage':'48%'},
    {'name':'Vitamin C','percentage':'21%'},
    {'name':'Vitamin K','percentage':'230%'},
    {'name':'Manganese','percentage':'5%'},

    {'name':'Carbonhydrate','percentage':'9%'},
    {'name':'Dietary Fiber','percentage':'16%'},
    {'name':'Sugar','percentage':'35%'},
    {'name':'Vitamin A','percentage':'377%'},
    {'name':'Vitamin C','percentage':'5%'},
    {'name':'Thiamin','percentage':'7%'},
    {'name':'Riboflav','percentage':'5%'},
    {'name':'Vitamin B','percentage':'14%'},
    {'name':'Pantothetic','percentage':'11%'},
    {'name':'Magnesium','percentage':'8%'},
    {'name':'Photsphorus','percentage':'6%'},
    {'name':'Potassium','percentage':'13%'},
    {'name':'Copper','percentage':'10%'},
    {'name':'Manganese','percentage':'17%'},

    {'name':'Calories','percentage':'6%'},
    {'name':'Total Fat','percentage':'6%'},
    {'name':'Protein','percentage':'40%'},
    {'name':'Vitamin A','percentage':'37%'},
    {'name':'Thiamin','percentage':'14%'},
    {'name':'Riboflav','percentage':'13%'},
    {'name':'Niacin','percentage':'37%'},
    {'name':'Vitamin B-6','percentage':'19%'},
    {'name':'Vitamin','percentage':'80%'},
    {'name':'Pantothetic','percentage':'9%'},
    {'name':'Iron','percentage':'5%'},
    {'name':'Magnesium','percentage':'11%'},
    {'name':'Photsphorus','percentage':'22%'},
    {'name':'Potassium','percentage':'6%'},
    {'name':'Selennium','percentage':'44%'},
    
    {'name':'Calories','percentage':'10%'},
    {'name':'Vitamin D','percentage':'63%'},
    {'name':'Vitamin E','percentage':'9%'},
    {'name':'Thiamin','percentage':'5%'},
    {'name':'Riboflav','percentage':'5%'},
    {'name':'Niacin','percentage':'24%'},
    {'name':'Vitamin B-6','percentage':'8%'},
    {'name':'Vitamin','percentage':'14%'},
    {'name':'Pantothetic','percentage':'6%'},
    {'name':'Calcium','percentage':'35%'},
    {'name':'Iron','percentage':'15%'},
    {'name':'Magnesium','percentage':'9%'},
    {'name':'Photsphorus','percentage':'45%'},
    {'name':'Potassium','percentage':'10%'},
    {'name':'Sodium','percentage':'19%'},
    {'name':'Zinc','percentage':'8%'},
    {'name':'Copper','percentage':'9%'},
    {'name':'Manganese','percentage':'5%'},
    {'name':'Selennium','percentage':'69%'},

    {'name':'Calories','percentage':'5%'},
    {'name':'Total Fat','percentage':'7%'},
    {'name':'Protein','percentage':'35%'},
    {'name':'Thiamin','percentage':'7%'},
    {'name':'Riboflav','percentage':'5%'},
    {'name':'Niacin','percentage':'23%'},
    {'name':'Vitamin B-6','percentage':'17%'},
    {'name':'Vitamin','percentage':'20%'},
    {'name':'Pantothetic','percentage':'8%'},
    {'name':'Calcium','percentage':'6%'},
    {'name':'Magnesium','percentage':'7%'},
    {'name':'Photsphorus','percentage':'23%'},
    {'name':'Potassium','percentage':'12%'},
    {'name':'Zinc','percentage':'6%'},
    {'name':'Manganese','percentage':'7%'},
    {'name':'Selennium','percentage':'15%'},

    {'name':'Calories','percentage':'9%'},
    {'name':'Protein','percentage':'32%'},
    {'name':'Riboflav','percentage':'16%'},
    {'name':'Niacin','percentage':'39%'},
    {'name':'Vitamin B-6','percentage':'17%'},
    {'name':'Vitamin','percentage':'6%'},
    {'name':'Pantothetic','percentage':'7%'},
    {'name':'Calcium','percentage':'1%'},
    {'name':'Iron','percentage':'8%'},
    {'name':'Magnesium','percentage':'16%'},
    {'name':'Photsphorus','percentage':'18%'},
    {'name':'Potassium','percentage':'8%'},
    {'name':'Zinc','percentage':'4%'},
    {'name':'Selennium','percentage':'54%'},

    {'name':'Calories','percentage':'6%'},
    {'name':'Protein','percentage':'35%'},
    {'name':'Riboflav','percentage':'13%'},
    {'name':'Niacin','percentage':'60%'},
    {'name':'Vitamin B-6','percentage':'6%'},
    {'name':'Vitamin','percentage':'6%'},
    {'name':'Pantothetic','percentage':'5%'},
    {'name':'Calcium','percentage':'12%'},
    {'name':'Iron','percentage':'15%'},
    {'name':'Magnesium','percentage':'9%'},
    {'name':'Photsphorus','percentage':'15%'},
    {'name':'Potassium','percentage':'9%'},
    {'name':'Zinc','percentage':'10%'},
    {'name':'Selennium','percentage':'44%'},

    {'name':'Calories','percentage':'6%'},
    {'name':'Protein','percentage':'36%'},
    {'name':'Riboflav','percentage':'9%'},
    {'name':'Niacin','percentage':'21%'},
    {'name':'Vitamin B-6','percentage':'21%'},
    {'name':'Vitamin','percentage':'14%'},
    {'name':'Pantothetic','percentage':'6%'},
    {'name':'Iron','percentage':'9%'},
    {'name':'Magnesium','percentage':'6%'},
    {'name':'Photsphorus','percentage':'6%'},
    {'name':'Potassium','percentage':'9%'},
    {'name':'Zinc','percentage':'30%'},
    {'name':'Selennium','percentage':'30%'},

    {'name':'Calories','percentage':'7%'},
    {'name':'Dietary Fiber','percentage':'42%'},
    {'name':'Total Fat','percentage':'13%'},
    {'name':'Protein','percentage':'9%'},
    {'name':'Calcium','percentage':'16%'},
    {'name':'Zinc','percentage':'7%'},
    {'name':'Manganese','percentage':'30%'},

    {'name':'Carbohydrate','percentage':'3%'},
    {'name':'Dietary Fiber','percentage':'24%'},
    {'name':'Sugar','percentage':'20%'},
    {'name':'Protein','percentage':'5%'},
    {'name':'Vitamin C','percentage':'187%'},
    {'name':'Vitamin K','percentage':'2%'},
    {'name':'Niacin','percentage':'1%'},
    {'name':'Vitamin','percentage':'6%'},
    {'name':'Pantothetic','percentage':'4%'},
    {'name':'Magnesium','percentage':'4%'},

    {'name':'Dietary Fiber','percentage':'5%'},
    {'name':'Sugar','percentage':'16%'},
    {'name':'Vitamin C','percentage':'273%'},
    {'name':'Vitamin K','percentage':'9%'},
    {'name':'Vitamin B-6','percentage':'6%'},
    {'name':'Calcium','percentage':'6%'},
    {'name':'Magnesium','percentage':'8%'},
    {'name':'Photsphorus','percentage':'4%'},
    {'name':'Potassium','percentage':'16%'},

    {'name':'Dietary Fiber','percentage':'2%'},
    {'name':'Sugar','percentage':'1%'},
    {'name':'Vitamin C','percentage':'25%'},
    {'name':'Vitamin B-6','percentage':'11%'},
    {'name':'Iron','percentage':'3%'},
    {'name':'Magnesium','percentage':'4%'},
    {'name':'Potassium','percentage':'9%'},
    {'name':'Zinc','percentage':'6%'},
    {'name':'Copper','percentage':'18%'},

    {'name':'Calories','percentage':'6%'},
    {'name':'Sugar','percentage':'8%'},

    {'name':'Sugar','percentage':'8%'},
    {'name':'Vitamin A','percentage':'7%'},

    {'name':'Carbohydrate','percentage':'7%'},

    {'name':'Calories','percentage':'6%'},
    {'name':'Sugar','percentage':'1%'},
    {'name':'Vitamin E','percentage':'10%'},
    {'name':'Vitamin K','percentage':'10%'},

    {'name':'Calories','percentage':'7%'},
    {'name':'Sugar','percentage':'3%'},
    {'name':'Vitamin E','percentage':'26%'},

    {'name':'Carbohydrate','percentage':'5%'},
    {'name':'Dietary Fiber','percentage':'10%'},
    {'name':'Sugar','percentage':'40%'},
    {'name':'Vitamin A','percentage':'31%'},
    {'name':'Vitamin C','percentage':'144%'},
    {'name':'Vitamin E','percentage':'5%'},
    {'name':'Vitamin K','percentage':'5%'},
    {'name':'Iron','percentage':'1%'},
    {'name':'Potassium','percentage':'10%'},

    {'name':'Calories','percentage':'7%'},
    {'name':'Sugar','percentage':'50%'},
    {'name':'Total Fat','percentage':'12%'},
    {'name':'Protein','percentage':'17%'},
    {'name':'Vitamin A','percentage':'5%'},
    {'name':'Thiamin','percentage':'5%'},
    {'name':'Riboflav','percentage':'20%'},
    {'name':'Vitamin','percentage':'8%'},
    {'name':'Pantothetic','percentage':'10%'},
    {'name':'Calcium','percentage':'30%'},
    {'name':'Magnesium','percentage':'7%'},
    {'name':'Photsphorus','percentage':'23%'},
    {'name':'Potassium','percentage':'11%'},
    {'name':'Sodium','percentage':'5%'},
    {'name':'Zinc','percentage':'10%'},
    {'name':'Selennium','percentage':'8%'},

    {'name':'Calories','percentage':'10%'},
    {'name':'Carbohydrate','percentage':'17%'},
    {'name':'Dietary Fiber','percentage':'23%'},
    {'name':'Sugar','percentage':'110%'},
    {'name':'Protein','percentage':'5%'},
    {'name':'Vitamin C','percentage':'33%'},
    {'name':'Thiamin','percentage':'5%'},
    {'name':'Riboflav','percentage':'10%'},
    {'name':'Niacin','percentage':'7%'},
    {'name':'Vitamin B-6','percentage':'41%'},
    {'name':'Vitamin','percentage':'3%'},
    {'name':'Calcium','percentage':'8%'},
    {'name':'Photsphorus','percentage':'15%'},
    {'name':'Potassium','percentage':'5%'},
    {'name':'Sodium','percentage':'23%'},
    {'name':'Magnesium','percentage':'9%'},
    {'name':'Selennium','percentage':'30%'},

    {'name':'Vitamin K','percentage':'12%'},
    {'name':'Potassium','percentage':'5%'},
    {'name':'Copper','percentage':'5%'},
    {'name':'Manganese','percentage':'5%'},
    
    {'name':'Dietary Fiber','percentage':'12%'},
    {'name':'Vitamin C','percentage':'149%'},
    {'name':'Magnesium','percentage':'5%'},
    {'name':'Potassium','percentage':'7%'},
    {'name':'Manganese','percentage':'29%'},

    {'name':'Dietary Fiber','percentage':'15%'},
    {'name':'Vitamin A','percentage':'15%'},
    {'name':'Vitamin C','percentage':'20%'},
    {'name':'Vitamin K','percentage':'20%'},
    {'name':'Thiamin','percentage':'6%'},
    {'name':'Riboflav','percentage':'7%'},
    {'name':'Iron','percentage':'6%'},
    {'name':'Magnesium','percentage':'7%'},
    {'name':'Potassium','percentage':'7%'},
    {'name':'Manganese','percentage':'12%'},

    {'name':'Calories','percentage':'5%'},
    {'name':'Carbohydrate','percentage':'6%'},
    {'name':'Dietary Fiber','percentage':'17%'},
    {'name':'Protein','percentage':'12%'},
    {'name':'Thiamin','percentage':'17%'},
    {'name':'Riboflav','percentage':'3%'},
    {'name':'Iron','percentage':'8%'},
    {'name':'Magnesium','percentage':'12%'},
    {'name':'Potassium','percentage':'12%'},
    {'name':'Zinc','percentage':'7%'},
    {'name':'Copper','percentage':'12%'},
    {'name':'Manganese','percentage':'15%'},

    {'name':'Dietary Fiber','percentage':'28%'},
    {'name':'Protein','percentage':'8%'},
    {'name':'Vitamin K','percentage':'24%'},
    {'name':'Thiamin','percentage':'6%'},
    {'name':'Riboflav','percentage':'5%'},
    {'name':'Niacin','percentage':'7%'},
    {'name':'Vitamin B-6','percentage':'7%'},
    {'name':'Calcium','percentage':'6%'},
    {'name':'Iron','percentage':'9%'},
    {'name':'Magnesium','percentage':'19%'},
    {'name':'Photsphorus','percentage':'12%'},
    {'name':'Potassium','percentage':'14%'},
    {'name':'Sodium','percentage':'5%'},
    {'name':'Copper','percentage':'15%'},
    {'name':'Manganese','percentage':'16%'},

    {'name':'Vitamin K','percentage':'1%'},

    {'name':'Vitamin K','percentage':'16%'},
    {'name':'Potassium','percentage':'1%'},
    
   

    


]



var foodInfo = [
    {'gi-level':'Low','color':'Brown','category':'Legumes','amount':'1oz','url':"background: #000 url('images/walnut2.jpg') no-repeat"},
    {'gi-level':'High','color':'white','category':'Legumes','amount':'1oz','url':"background: #000 url('images/walnut2.jpg') no-repeat"},

]