var nutriInfo2 = [
    {'name':'Sugar','percentage':'20%'},
    {'name':'Vitamin A','percentage':'25%'},
    {'name':'Vitamin C','percentage':'32%'},
    {'name':'Vitamin K','percentage':'15%'},
    {'name':'Vitamin B-6','percentage':'6%'},
    {'name':'Potassium','percentage':'10%'},

    {'name':'Dietary fiber','percentage':'14%'},
    {'name':'Sugar','percentage':'30%'},
    {'name':'Vitamin A','percentage':'428%'},
    {'name':'Vitamin C','percentage':'13%'},
    {'name':'Vitamin K','percentage':'21%'},
    {'name':'Thiamin','percentage':'6%'},
    {'name':'Niacin','percentage':'6%'},
    {'name':'Vitamin B-6','percentage':'9%'},
    {'name':'Potassium','percentage':'12%'},

    {'name':'Sugar','percentage':'12%'},
    {'name':'Vitamin A','percentage':'428%'},
    {'name':'Vitamin C','percentage':'13%'},

    {'name':'Carbohydrate','percentage':'9%'},
    {'name':'Dietary Fiber','percentage':'23%'},
    {'name':'Sugar','percentage':'90%'},
    {'name':'Vitamin C','percentage':'24%'},
    {'name':'Vitamin K','percentage':'29%'},
    {'name':'Thiamin','percentage':'6%'},
    {'name':'Vitamin B-6','percentage':'6%'},
    {'name':'Pantothenic','percentage':'5%'},
    {'name':'Photsphorus','percentage':'5%'},
    {'name':'Potassium','percentage':'10%'},
    {'name':'Copper','percentage':'11%'},
    {'name':'Manganese','percentage':'9%'},

    {'name':'Iron','percentage':'6%'},
    {'name':'Manganese','percentage':'6%'},

    {'name':'Dietary Fiber','percentage':'10%'},
    {'name':'Total Fat','percentage':'11%'},
    {'name':'Thiamin','percentage':'11%'},
    {'name':'Iron','percentage':'6%'},
    {'name':'Magnesium','percentage':'12%'},
    {'name':'Photsphorus','percentage':'11%'},
    {'name':'Zinc','percentage':'10%'},
    {'name':'Copper','percentage':'10%'},
    {'name':'Manganese','percentage':'10%'},

    {'name':'Manganese','percentage':'28%'},

    {'name':'Total Fat','percentage':'6%'},
    {'name':'Protein','percentage':'33%'},
    {'name':'Vitamin A','percentage':'15%'},
    {'name':'Vitamin D','percentage':'27%'},
    {'name':'Vitamin E','percentage':'6%'},
    {'name':'Thiamin','percentage':'3%'},
    {'name':'Vitamin B-6','percentage':'12%'},
    {'name':'Vitamin','percentage':'7%'},
    {'name':'Pantothenic','percentage':'21%'},
    {'name':'Calcium','percentage':'6%'},
    {'name':'Iron','percentage':'12%'},
    {'name':'Magnesium','percentage':'3%'},
    {'name':'Photsphorus','percentage':'27%'},
    {'name':'Potassium','percentage':'3%'},
    {'name':'Sodium','percentage':'9%'},
    {'name':'Zinc','percentage':'12%'},
    {'name':'Copper','percentage':'6%'},
    {'name':'Selennium','percentage':'57%'},

]