var nutriInfo3 = [
    {'name':'Calories','percentage':'14%'},
    {'name':'Carbohydrate','percentage':'20%'},
    {'name':'Dietary Fiber','percentage':'38%'},
    {'name':'Protein','percentage':'18%'},
    {'name':'Riboflav','percentage':'6%'},
    {'name':'Niacin','percentage':'14%'},
    {'name':'Vitamin B-6','percentage':'10%'},
    {'name':'Iron','percentage':'14%'},
    {'name':'Riboflav','percentage':'6%'},
    {'name':'Photsphorus','percentage':'28%'},
    {'name':'Zinc','percentage':'18%'},
    {'name':'Copper','percentage':'18%'},
    {'name':'Selennium','percentage':'50%'},
    
    {'name':'Vitamin C','percentage':'5%'},
    {'name':'Vitamin B-6','percentage':'6%'},

    {'name':'Calories','percentage':'7%'},
    {'name':'Total Fat','percentage':'12%'},
    {'name':'Protein','percentage':'36%'},
    {'name':'Niacin','percentage':'43%'},
    {'name':'Vitamin B-6','percentage':'23%'},
    {'name':'Vitamin','percentage':'6%'},
    {'name':'Pantothenic','percentage':'7%'},
    {'name':'Magnesium','percentage':'5%'},
    {'name':'Photsphorus','percentage':'15%'},
    {'name':'Potassium','percentage':'5%'},
    {'name':'Zinc','percentage':'5%'},
    {'name':'Selennium','percentage':'50%'},

    {'name':'Calories','percentage':'5%'},
    {'name':'Protein','percentage':'35%'},
    {'name':'Vitamin D','percentage':'32%'},
    {'name':'Vitamin E','percentage':'5%'},
    {'name':'Niacin','percentage':'11%'},
    {'name':'Vitamin','percentage':'7%'},
    {'name':'Iron','percentage':'11%'},
    {'name':'Magnesium','percentage':'8%'},
    {'name':'Photsphorus','percentage':'17%'},
    {'name':'Sodium','percentage':'5%'},
    {'name':'Zinc','percentage':'6%'},
    {'name':'Copper','percentage':'11%'},
    {'name':'Selennium','percentage':'46%'},

    {'name':'Calories','percentage':'19%'},
    {'name':'Dietary Fiber','percentage':'43%'},
    {'name':'Total Fat','percentage':'27%'},
    {'name':'Protein','percentage':'66%'},
    {'name':'Vitamin A','percentage':'9%'},
    {'name':'Vitamin C','percentage':'124%'},
    {'name':'Thiamin','percentage':'74%'},
    {'name':'Riboflav','percentage':'26%'},
    {'name':'Niacin','percentage':'21%'},
    {'name':'Vitamin B-6','percentage':'8%'},
    {'name':'Calcium','percentage':'50%'},
    {'name':'Iron','percentage':'50%'},
    {'name':'Magnesium','percentage':'42%'},
    {'name':'Photsphorus','percentage':'50%'},
    {'name':'Potassium','percentage':'45%'},
    {'name':'Zinc','percentage':'17%'},
    {'name':'Copper','percentage':'16%'},
    {'name':'Manganese','percentage':'70%'},

    {'name':'Protein','percentage':'6%'},
    {'name':'Photsphorus','percentage':'5%'},

    {'name':'Calories','percentage':'6%'},
    {'name':'Protein','percentage':'32%'},
    {'name':'Riboflav','percentage':'5%'},
    {'name':'Niacin','percentage':'19%'},
    {'name':'Vitamin B-6','percentage':'17%'},
    {'name':'Vitamin','percentage':'4%'},
    {'name':'Pantothenic','percentage':'5%'},
    {'name':'Iron','percentage':'5%'},
    {'name':'Magnesium','percentage':'5%'},
    {'name':'Photsphorus','percentage':'14%'},
    {'name':'Potassium','percentage':'6%'},
    {'name':'Zinc','percentage':'8%'},
    {'name':'Selennium','percentage':'25%'},
    
    {'name':'Protein','percentage':'33%'},
    {'name':'Niacin','percentage':'15%'},
    {'name':'Vitamin B-6','percentage':'6%'},
    {'name':'Vitamin','percentage':'3%'},
    {'name':'Magnesium','percentage':'6%'},
    {'name':'Photsphorus','percentage':'15%'},
    {'name':'Potassium','percentage':'6%'},
    {'name':'Selennium','percentage':'64%'},

    {'name':'Calories','percentage':'14%'},
    {'name':'Carbohydrate','percentage':'13%'},
    {'name':'Dietary Fiber','percentage':'21%'},
    {'name':'Protein','percentage':'16%'},
    {'name':'Vitamin E','percentage':'6%'},
    {'name':'Thiamin','percentage':'13%'},
    {'name':'Riboflav','percentage':'12%'},
    {'name':'Vitamin B-6','percentage':'11%'},
    {'name':'Calcium','percentage':'3%'},
    {'name':'Iron','percentage':'15%'},
    {'name':'Magnesium','percentage':'30%'},
    {'name':'Photsphorus','percentage':'28%'},
    {'name':'Potassium','percentage':'9%'},
    {'name':'Zinc','percentage':'13%'},
    {'name':'Copper','percentage':'18%'},
    {'name':'Manganese','percentage':'58%'},

    {'name':'Protein','percentage':'29%'},
    {'name':'Niacin','percentage':'5%'},
    {'name':'Vitamin B-6','percentage':'6%'},
    {'name':'Vitamin','percentage':'4%'},
    {'name':'Magnesium','percentage':'12%'},
    {'name':'Potassium','percentage':'8%'},
    {'name':'Sodium','percentage':'6%'},
    {'name':'Iron','percentage':'1%'},
    {'name':'Selennium','percentage':'27%'},

    {'name':'Calories','percentage':'6%'},
    {'name':'Total Fat','percentage':'11%'},
    {'name':'Protein','percentage':'19%'},
    {'name':'Vitamin','percentage':'6%'},
    {'name':'Zinc','percentage':'15%'},
    {'name':'Photsphorus','percentage':'11%'},
    {'name':'Potassium','percentage':'5%'},
    {'name':'Sodium','percentage':'26%'},
    {'name':'Iron','percentage':'8%'},

    {'name':'Dietary Fiber','percentage':'5%'},
    {'name':'Vitamin B-6','percentage':'7%'},

    {'name':'Calories','percentage':'6%'},
    {'name':'Total Fat','percentage':'6%'},
    {'name':'Protein','percentage':'36%'},
    {'name':'Thiamin','percentage':'12%'},
    {'name':'Riboflav','percentage':'15%'},
    {'name':'Vitamin B-6','percentage':'21%'},
    {'name':'Vitamin','percentage':'36%'},
    {'name':'Pantothenic','percentage':'9%'},
    {'name':'Iron','percentage':'18%'},
    {'name':'Photsphorus','percentage':'18%'},
    {'name':'Potassium','percentage':'6%'},
    {'name':'Zinc','percentage':'21%'},
    {'name':'Copper','percentage':'6%'},
    {'name':'Selennium','percentage':'42%'},

    {'name':'Calories','percentage':'8%'},
    {'name':'Dietary Fiber','percentage':'10%'},
    {'name':'Total Fat','percentage':'22%'},
    {'name':'Protein','percentage':'12%'},
    {'name':'Vitamin E','percentage':'47%'},
    {'name':'Thiamin','percentage':'28%'},
    {'name':'Riboflav','percentage':'6%'},
    {'name':'Niacin','percentage':'12%'},
    {'name':'Vitamin B-6','percentage':'19%'},
    {'name':'Iron','percentage':'8%'},
    {'name':'Magnesium','percentage':'23%'},
    {'name':'Photsphorus','percentage':'18%'},
    {'name':'Potassium','percentage':'5%'},
    {'name':'Zinc','percentage':'9%'},
    {'name':'Copper','percentage':'25%'},
    {'name':'Manganese','percentage':'17%'},
    {'name':'Selennium','percentage':'21%'},

    {'name':'Dietary Fiber','percentage':'13%'},
    {'name':'Sugar','percentage':'30%'},
    {'name':'Vitamin A','percentage':'93%'},
    {'name':'Vitamin C','percentage':'317%'},
    {'name':'Vitamin E','percentage':'12%'},
    {'name':'Vitamin K','percentage':'9%'},
    {'name':'Thiamin','percentage':'5%'},
    {'name':'Riboflav','percentage':'7%'},
    {'name':'Niacin','percentage':'7%'},
    {'name':'Vitamin B-6','percentage':'22%'},
    {'name':'Pantothenic','percentage':'5%'},
    {'name':'Potassium','percentage':'9%'},

    {'name':'Calories','percentage':'9%'},
    {'name':'Dietary Fiber','percentage':'11%'},
    {'name':'Sugar','percentage':'5%'},
    {'name':'Total Fat','percentage':'27%'},
    {'name':'Protein','percentage':'8%'},
    {'name':'Vitamin E','percentage':'21%'},
    {'name':'Thiamin','percentage':'6%'},
    {'name':'Vitamin B-6','percentage':'9%'},
    {'name':'Pantothenic','percentage':'3%'},
    {'name':'Iron','percentage':'7%'},
    {'name':'Magnesium','percentage':'12%'},
    {'name':'Photsphorus','percentage':'9%'},
    {'name':'Potassium','percentage':'6%'},
    {'name':'Zinc','percentage':'5%'},
    {'name':'Manganese','percentage':'78%'},

    {'name':'Calories','percentage':'8%'},
    {'name':'Dietary Fiber','percentage':'12%'},
    {'name':'Sugar','percentage':'10%'},
    {'name':'Total Fat','percentage':'20%'},
    {'name':'Protein','percentage':'12%'},
    {'name':'Thiamin','percentage':'3%'},
    {'name':'Vitamin B-6','percentage':'18%'},
    {'name':'Pantothenic','percentage':'1%'},
    {'name':'Iron','percentage':'7%'},
    {'name':'Magnesium','percentage':'8%'},
    {'name':'Photsphorus','percentage':'14%'},
    {'name':'Zinc','percentage':'4%'},
    {'name':'Manganese','percentage':'18%'},

    {'name':'Dietary Fiber','percentage':'6%'},
    {'name':'Sugar','percentage':'10%'},
    {'name':'Protein','percentage':'7%'},
    {'name':'Vitamin K','percentage':'10%'},
    {'name':'Sodium','percentage':'2%'},
    {'name':'Pantothenic','percentage':'1%'},
    {'name':'Copper','percentage':'6%'},
    {'name':'Manganese','percentage':'12%'},

    {'name':'Carbohydrate','percentage':'7%'},
    {'name':'Dietary Fiber','percentage':'9%'},
    {'name':'Sugar','percentage':'70%'},
    {'name':'Vitamin C','percentage':'155%'},
    {'name':'Vitamin K','percentage':'1%'},
    {'name':'Thiamin','percentage':'1%'},
    {'name':'Vitamin B-6','percentage':'9%'},
    {'name':'Iron','percentage':'3%'},
    {'name':'Photsphorus','percentage':'1%'},
    {'name':'Copper','percentage':'9%'},
    {'name':'Manganese','percentage':'67%'},

    {'name':'Calories','percentage':'6%'},
    {'name':'Vitamin K','percentage':'27%'},
    {'name':'Vitamin','percentage':'6%'},
    {'name':'Pantothenic','percentage':'14%'},
    {'name':'Calcium','percentage':'1%'},
    {'name':'Magnesium','percentage':'6%'},
    {'name':'Sodium','percentage':'13%'},

    {'name':'Carbohydrate','percentage':'5%'},
    {'name':'Dietary Fiber','percentage':'32%'},
    {'name':'Vitamin E','percentage':'5%'},
    {'name':'Vitamin K','percentage':'12%'},
    {'name':'Pantothenic','percentage':'4%'},
    {'name':'Iron','percentage':'5%'},
    {'name':'Photsphorus','percentage':'4%'},
    {'name':'Copper','percentage':'6%'},
    {'name':'Manganese','percentage':'41%'},


    {'name':'Dietary Fiber','percentage':'11%'},
    {'name':'Sugar','percentage':'10%'},
    {'name':'Protein','percentage':'6%'},
    {'name':'Vitamin A','percentage':'20%'},
    {'name':'Vitamin C','percentage':'13%'},
    {'name':'Vitamin E','percentage':'8%'},
    {'name':'Vitamin K','percentage':'70%'},
    {'name':'Thiamin','percentage':'13%'},
    {'name':'Riboflav','percentage':'11%'},
    {'name':'Niacin','percentage':'7%'},
    {'name':'Vitamin B-6','percentage':'6%'},
    {'name':'Pantothenic','percentage':'8%'},
    {'name':'Iron','percentage':'16%'},
    {'name':'Magnesium','percentage':'5%'},
    {'name':'Photsphorus','percentage':'7%'},
    {'name':'Pantothenic','percentage':'8%'},
    {'name':'Copper','percentage':'13%'},
    {'name':'Manganese','percentage':'11%'},

    {'name':'Carbohydrate','percentage':'15%'},
    {'name':'Dietary Fiber','percentage':'45%'},
    {'name':'Vitamin C','percentage':'11%'},
    {'name':'Vitamin B-6','percentage':'5%'},
    {'name':'Pantothenic','percentage':'2%'},
    {'name':'Iron','percentage':'6%'},
    {'name':'Magnesium','percentage':'8%'},
    {'name':'Photsphorus','percentage':'5%'},
    {'name':'Copper','percentage':'5%'},
    {'name':'Manganese','percentage':'22%'},

    {'name':'Carbohydrate','percentage':'7%'},
    {'name':'Sugar','percentage':'75%'},
    {'name':'Photsphorus','percentage':'3%'},

    {'name':'Calories','percentage':'10%'},
    {'name':'Carbohydrate','percentage':'15%'},
    {'name':'Dietary Fiber','percentage':'24%'},
    {'name':'Protein','percentage':'7%'},
    {'name':'Thiamin','percentage':'9%'},
    {'name':'Riboflav','percentage':'6%'},
    {'name':'Niacin','percentage':'16%'},
    {'name':'Vitamin B-6','percentage':'9%'},
    {'name':'Pantothenic','percentage':'2%'},
    {'name':'Iron','percentage':'12%'},
    {'name':'Pantothenic','percentage':'2%'},
    {'name':'Copper','percentage':'8%'},
    {'name':'Manganese','percentage':'20%'},

    {'name':'Dietary Fiber','percentage':'11%'},
    {'name':'Protein','percentage':'2%'},
    {'name':'Photsphorus','percentage':'2%'},
    {'name':'Copper','percentage':'3%'},

    {'name':'Dietary Fiber','percentage':'13%'},
    {'name':'Sugar','percentage':'5%'},
    {'name':'Vitamin A','percentage':'7%'},
    {'name':'Vitamin C','percentage':'35%'},
    {'name':'Vitamin K','percentage':'66%'},
    {'name':'Copper','percentage':'5%'},

    {'name':'Calories','percentage':'5%'},
    {'name':'Carbohydrate','percentage':'9%'},
    {'name':'Dietary Fiber','percentage':'5%'},
    {'name':'Sugar','percentage':'90%'},
    {'name':'Vitamin C','percentage':'27%'},
    {'name':'Pantothenic','percentage':'1%'},

    {'name':'Calories','percentage':'3%'},
    {'name':'Carbohydrate','percentage':'6%'},
    {'name':'Dietary Fiber','percentage':'3%'},
    {'name':'Sugar','percentage':'13%'},
    {'name':'Vitamin C','percentage':'10%'},

    {'name':'Calories','percentage':'6%'},
    {'name':'Dietary Fiber','percentage':'2%'},
    {'name':'Total Fat','percentage':'26%'},
    {'name':'Protein','percentage':'5%'},
    {'name':'Vitamin B-6','percentage':'8%'},

    {'name':'Calories','percentage':'8%'},
    {'name':'Dietary Fiber','percentage':'12%'},
    {'name':'Sugar','percentage':'25%'},
    {'name':'Total Fat','percentage':'18%'},
    {'name':'Pantothenic','percentage':'1%'},
    {'name':'Iron','percentage':'19%'},
    {'name':'Copper','percentage':'25%'},
    {'name':'Manganese','percentage':'27%'},




]